import type {
  AnalyticsMetric,
  TokenTrendGranularity,
  TokenTrendResult,
  WorkHealthSummary,
} from "../../shared/analyticsTypes";
import type { ResolvedLocale } from "../../shared/i18nTypes";
import type {
  AgentTokenStats,
  DailyTokenStats,
  ModelPricing,
  ModelTokenStats,
  ProjectTokenStats,
  SessionStatsEntry,
  SessionTokenStats,
  UsageContext,
  UsageImportStatus,
} from "../../shared/usageTypes";
import { estimateTokenCost, resolveModelPricing } from "../../shared/modelPricing";
import { isUnknownProjectPath, sortProjectRows, UNKNOWN_PROJECT_PATH } from "../../shared/projectAttribution";

export type ReportRedactionOptions = {
  /** Replace session titles with generic labels */
  redactSessionTitles?: boolean;
  /** Replace model names with generic labels */
  redactModelNames?: boolean;
  /** Match the in-app trend granularity when opened from Analytics */
  trendGranularity?: TokenTrendGranularity;
  /** Match the in-app metric selection when opened from Analytics */
  metric?: AnalyticsMetric;
  /** Match the in-app agent filter when opened from Analytics */
  agent?: string;
  /** Match the in-app model filter when opened from Analytics */
  model?: string;
  /** Match the in-app project filter when opened from Analytics */
  projectPath?: string;
  /** Resolved UI locale at the time the report is opened */
  locale?: ResolvedLocale;
};

export type HtmlReportInput = {
  startDate: string;
  endDate: string;
  sessionStats: SessionStatsEntry[];
  daily: DailyTokenStats[];
  byProject?: ProjectTokenStats[];
  byModel: ModelTokenStats[];
  byAgent?: AgentTokenStats[];
  topSessions?: SessionTokenStats[];
  sessionContexts?: Record<string, UsageContext | undefined>;
  importStatus?: UsageImportStatus;
  trend?: TokenTrendResult;
  metric?: AnalyticsMetric;
  locale?: ResolvedLocale;
  workHealth?: Pick<WorkHealthSummary, "signals">;
  pricing: ModelPricing[];
  redaction?: ReportRedactionOptions;
};

type ReportTrendPoint = {
  key: string;
  label: string;
  input: number;
  output: number;
  cache: number;
  total: number;
  requests: number;
};

type SvgPoint = ReportTrendPoint & {
  x: number;
  totalY: number;
  inputY: number;
  outputY: number;
  cacheY: number;
};

type ReportCopy = {
  htmlLang: ResolvedLocale;
  title: string;
  sessions: string;
  agent: string;
  total: string;
  breakdown: string;
  tokenUsage: string;
  totalTokens: string;
  requests: string;
  input: string;
  output: string;
  cache: string;
  cacheRead: string;
  cacheHit: string;
  cacheHitRate: string;
  estimatedCost: string;
  topAgent: string;
  topModel: string;
  dailyTrend: string;
  workHealth: string;
  compactBreakdown: string;
  project: string;
  unknownProject: string;
  byModel: string;
  byAgent: string;
  topSessions: string;
  model: string;
  cost: string;
  context: string;
  session: string;
  tokens: string;
  lastSeen: string;
  generatedBy: string;
  redacted: string;
  redactedSessionTitles: string;
  redactedModelNames: string;
  redactedSessionPrefix: string;
  redactedModel: string;
  backfill: string;
  notCompleted: string;
  claudeRows: string;
  codexRows: string;
  error: string;
  usageOnly: string;
  metric: Record<AnalyticsMetric, string>;
  workHealthSignal: Record<string, string>;
  workHealthDetail: Record<string, string>;
  status: Record<string, string>;
};

const REPORT_COPY: Record<ResolvedLocale, ReportCopy> = {
  en: {
    htmlLang: "en",
    title: "CodePal Usage Report",
    sessions: "Sessions",
    agent: "Agent",
    total: "Total",
    breakdown: "Breakdown",
    tokenUsage: "Token Usage",
    totalTokens: "Total Tokens",
    requests: "Requests",
    input: "Input",
    output: "Output",
    cache: "Cache",
    cacheRead: "Cache Read",
    cacheHit: "Cache Hit",
    cacheHitRate: "Cache Hit Rate",
    estimatedCost: "Estimated Cost",
    topAgent: "Top Agent",
    topModel: "Top Model",
    dailyTrend: "Daily Trend",
    workHealth: "Work Health",
    compactBreakdown: "Compact Breakdown",
    project: "Project",
    unknownProject: "Unidentified Project",
    byModel: "By Model",
    byAgent: "By Agent",
    topSessions: "Top Sessions",
    model: "Model",
    cost: "Cost",
    context: "Context",
    session: "Session",
    tokens: "Tokens",
    lastSeen: "Last Seen",
    generatedBy: "Generated by CodePal",
    redacted: "Redacted",
    redactedSessionTitles: "session titles",
    redactedModelNames: "model names",
    redactedSessionPrefix: "Session",
    redactedModel: "model",
    backfill: "Backfill",
    notCompleted: "not completed",
    claudeRows: "Claude rows",
    codexRows: "Codex rows",
    error: "Error",
    usageOnly: "usage-only",
    metric: {
      tokens: "Total",
      requests: "Requests",
      cost: "Cost",
      cacheHit: "Cache Hit",
    },
    workHealthSignal: {
      attention: "Attention",
      longest_wait: "Longest wait",
      unrecovered_failure: "Unrecovered failures",
      context_near_full: "Context near full",
      cost_anomaly: "Cost anomaly",
    },
    workHealthDetail: {
      attention: "{count} active items need review",
      attentionZero: "No high-priority attention items",
      longest_wait: "Longest currently waiting item",
      longest_wait_zero: "No waiting items",
      unrecovered_failure: "{count} failed sessions without recovery",
      unrecovered_failure_zero: "No unrecovered failures",
      context_near_full: "{count} sessions above the context threshold",
      context_near_full_zero: "No high-context signal is available",
      cost_anomaly: "vs previous equal-length range",
      cost_new: "No previous cost baseline",
    },
    status: {
      completed: "completed",
      running: "running",
      waiting: "waiting",
      error: "error",
      idle: "idle",
      offline: "offline",
      unknown: "usage-only",
    },
  },
  "zh-CN": {
    htmlLang: "zh-CN",
    title: "CodePal 用量报告",
    sessions: "会话",
    agent: "Agent",
    total: "总计",
    breakdown: "拆分",
    tokenUsage: "Token 用量",
    totalTokens: "总 Token",
    requests: "请求数",
    input: "Input",
    output: "Output",
    cache: "Cache",
    cacheRead: "Cache 读取",
    cacheHit: "Cache 命中",
    cacheHitRate: "Cache 命中率",
    estimatedCost: "估算费用",
    topAgent: "主要 Agent",
    topModel: "主要模型",
    dailyTrend: "每日趋势",
    workHealth: "工作健康",
    compactBreakdown: "精简拆分",
    project: "项目",
    unknownProject: "未识别项目",
    byModel: "按模型",
    byAgent: "按 Agent",
    topSessions: "高用量会话",
    model: "模型",
    cost: "费用",
    context: "上下文",
    session: "会话",
    tokens: "Token",
    lastSeen: "最后出现",
    generatedBy: "由 CodePal 生成",
    redacted: "已脱敏",
    redactedSessionTitles: "会话标题",
    redactedModelNames: "模型名称",
    redactedSessionPrefix: "会话",
    redactedModel: "模型",
    backfill: "历史补齐",
    notCompleted: "未完成",
    claudeRows: "Claude 行数",
    codexRows: "Codex 行数",
    error: "错误",
    usageOnly: "仅用量",
    metric: {
      tokens: "总计",
      requests: "请求数",
      cost: "费用",
      cacheHit: "Cache 命中",
    },
    workHealthSignal: {
      attention: "需处理",
      longest_wait: "最长等待",
      unrecovered_failure: "失败未恢复",
      context_near_full: "上下文接近满载",
      cost_anomaly: "成本异常",
    },
    workHealthDetail: {
      attention: "{count} 个活跃项需要关注",
      attentionZero: "当前没有高优先级关注项",
      longest_wait: "等待项中最长的一项",
      longest_wait_zero: "当前没有等待项",
      unrecovered_failure: "{count} 个失败 session 尚未恢复",
      unrecovered_failure_zero: "没有未恢复失败",
      context_near_full: "{count} 个 session 超过上下文阈值",
      context_near_full_zero: "没有可用的高上下文信号",
      cost_anomaly: "较上一等长周期",
      cost_new: "上一等长周期无成本基线",
    },
    status: {
      completed: "已完成",
      running: "运行中",
      waiting: "等待中",
      error: "错误",
      idle: "空闲",
      offline: "离线",
      unknown: "仅用量",
    },
  },
};

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function fmtTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function fmtCost(usd: number, locale: ResolvedLocale = "en"): string {
  return locale === "zh-CN" ? `US$${usd.toFixed(2)}` : `$${usd.toFixed(2)}`;
}

function fmtHeroCost(usd: number, locale: ResolvedLocale = "en"): string {
  if (usd > 0 && usd < 1) {
    return locale === "zh-CN" ? "<US$1" : "<$1";
  }
  const rounded = Math.round(usd);
  return locale === "zh-CN" ? `US$${rounded}` : `$${rounded}`;
}

function fmtHeroTokens(n: number): string {
  if (n >= 1_000_000) return `${Math.round(n / 1_000_000)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`;
  return String(Math.round(n));
}

function contextPercent(context: UsageContext | undefined): number | null {
  if (!context) return null;
  const percent =
    typeof context.percent === "number"
      ? context.percent
      : typeof context.used === "number" && typeof context.max === "number" && context.max > 0
        ? (context.used / context.max) * 100
        : undefined;
  return typeof percent === "number" && Number.isFinite(percent)
    ? Math.max(0, Math.round(percent))
    : null;
}

function contextTone(percent: number): "normal" | "notice" | "warning" | "danger" {
  if (percent >= 95) return "danger";
  if (percent >= 85) return "warning";
  if (percent >= 70) return "notice";
  return "normal";
}

function contextDetail(context: UsageContext | undefined): string {
  if (typeof context?.used !== "number" || typeof context.max !== "number") {
    return "";
  }
  return `${fmtTokens(context.used)} / ${fmtTokens(context.max)}`;
}

function fmtDateTime(ms: number, locale: ResolvedLocale = "en"): string {
  return new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(ms));
}

function shortSessionId(sessionId: string): string {
  return sessionId.length > 18 ? `${sessionId.slice(0, 8)}…${sessionId.slice(-4)}` : sessionId;
}

function interpolate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{([^}]+)\}/g, (_match, key: string) =>
    String(values[key] ?? ""),
  );
}

function statusLabel(status: string, copy: ReportCopy): string {
  return copy.status[status] ?? (status === "unknown" ? copy.usageOnly : status);
}

function estimateCost(
  stats: { inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheCreationTokens: number },
  pricing: ModelPricing[],
  model?: string,
): number {
  const match = (model
    ? resolveModelPricing({ model }, pricing, { allowModelFallback: false })
    : undefined) ?? resolveModelPricing({ model: "claude-sonnet-4-5-20250929" }, pricing, {
      allowModelFallback: false,
    });
  if (!match) return 0;
  return estimateTokenCost(
    {
      ...stats,
      model: match.pricing.modelId,
    },
    [match.pricing],
    { allowModelFallback: false },
  ) ?? 0;
}

const AGENT_LABELS: Record<string, string> = {
  claude: "Claude",
  codex: "Codex",
  codebuddy: "CodeBuddy",
  cursor: "Cursor",
  goland: "GoLand",
  pycharm: "PyCharm",
};

const TREND_WIDTH = 900;
const TREND_HEIGHT = 260;
const TREND_PAD = { top: 24, right: 28, bottom: 38, left: 64 };

function seriesPath(points: Array<{ x: number; y: number }>): string {
  if (points.length === 0) return "";
  return points.map((point, index) =>
    `${index === 0 ? "M" : "L"} ${round(point.x)} ${round(point.y)}`,
  ).join(" ");
}

function areaPath(points: Array<{ x: number; y: number }>, baselineY: number): string {
  if (points.length === 0) return "";
  const first = points[0];
  const last = points[points.length - 1];
  return [
    `M ${round(first.x)} ${round(baselineY)}`,
    `L ${round(first.x)} ${round(first.y)}`,
    ...points.slice(1).map((point) => `L ${round(point.x)} ${round(point.y)}`),
    `L ${round(last.x)} ${round(baselineY)}`,
    "Z",
  ].join(" ");
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

function formatMetricValue(value: number, metric: AnalyticsMetric = "tokens"): string {
  if (metric === "cost") return fmtCost(value);
  if (metric === "cacheHit") return `${Math.round(value)}%`;
  return fmtTokens(value);
}

function twoDigit(value: number): string {
  return value.toString().padStart(2, "0");
}

function formatTrendBucketLabel(timestamp: number, granularity: TokenTrendGranularity): string {
  const date = new Date(timestamp);
  const monthDay = `${twoDigit(date.getMonth() + 1)}-${twoDigit(date.getDate())}`;
  if (granularity === "day") return monthDay;
  return `${monthDay} ${twoDigit(date.getHours())}:${twoDigit(date.getMinutes())}`;
}

function metricLabel(metric: AnalyticsMetric = "tokens", copy: ReportCopy = REPORT_COPY.en): string {
  return copy.metric[metric];
}

function buildReportTrendPoints(input: HtmlReportInput): ReportTrendPoint[] {
  const metric = input.metric ?? "tokens";
  if (input.trend?.points.length) {
    const byBucket = new Map<number, ReportTrendPoint & { cacheRead: number; inputLike: number }>();
    for (const point of input.trend.points) {
      const existing = byBucket.get(point.bucketStart) ?? {
        key: String(point.bucketStart),
        label: formatTrendBucketLabel(point.bucketStart, input.trend.granularity),
        input: 0,
        output: 0,
        cache: 0,
        total: 0,
        requests: 0,
        cacheRead: 0,
        inputLike: 0,
      };
      existing.requests += point.requestCount;
      if (metric === "requests") {
        existing.total += point.requestCount;
      } else if (metric === "cost") {
        existing.total += estimateCost(point, input.pricing, point.model);
      } else if (metric === "cacheHit") {
        existing.inputLike += point.inputTokens + point.cacheReadTokens + point.cacheCreationTokens;
        existing.cacheRead += point.cacheReadTokens;
      } else {
        existing.input += point.inputTokens;
        existing.output += point.outputTokens;
        existing.cache += point.cacheReadTokens + point.cacheCreationTokens;
        existing.total += point.totalTokens;
      }
      byBucket.set(point.bucketStart, existing);
    }
    return Array.from(byBucket.values())
      .map((point) =>
        metric === "cacheHit"
          ? {
              ...point,
              total: point.inputLike > 0 ? (point.cacheRead / point.inputLike) * 100 : 0,
              input: 0,
              output: 0,
              cache: 0,
            }
          : point,
      )
      .sort((a, b) => Number(a.key) - Number(b.key));
  }

  const byDate = new Map<string, ReportTrendPoint>();
  for (const daily of input.daily) {
    const existing = byDate.get(daily.date) ?? {
      key: daily.date,
      label: daily.date.slice(5),
      input: 0,
      output: 0,
      cache: 0,
      total: 0,
      requests: 0,
    };
    existing.input += daily.inputTokens;
    existing.output += daily.outputTokens;
    existing.cache += daily.cacheReadTokens + daily.cacheCreationTokens;
    existing.total += daily.inputTokens + daily.outputTokens + daily.cacheReadTokens + daily.cacheCreationTokens;
    existing.requests += daily.requestCount;
    byDate.set(daily.date, existing);
  }
  return Array.from(byDate.values()).sort((a, b) => a.key.localeCompare(b.key));
}

function renderTrendChart(
  points: ReportTrendPoint[],
  metric: AnalyticsMetric = "tokens",
  copy: ReportCopy = REPORT_COPY.en,
): string {
  if (points.length === 0) return "";

  const chartWidth = TREND_WIDTH - TREND_PAD.left - TREND_PAD.right;
  const chartHeight = TREND_HEIGHT - TREND_PAD.top - TREND_PAD.bottom;
  const baselineY = TREND_PAD.top + chartHeight;
  const maxValue = metric === "tokens"
    ? Math.max(1, ...points.flatMap((point) => [point.total, point.input, point.output, point.cache]))
    : Math.max(1, ...points.map((point) => point.total));
  const xStep = points.length > 1 ? chartWidth / (points.length - 1) : 0;
  const scaleY = (value: number) => baselineY - (value / maxValue) * chartHeight;
  const svgPoints: SvgPoint[] = points.map((point, index) => {
    const x = points.length === 1 ? TREND_PAD.left + chartWidth / 2 : TREND_PAD.left + index * xStep;
    return {
      ...point,
      x,
      totalY: scaleY(point.total),
      inputY: scaleY(point.input),
      outputY: scaleY(point.output),
      cacheY: scaleY(point.cache),
    };
  });

  const yTicks = [0, 0.25, 0.5, 0.75, 1].map((ratio) => {
    const y = baselineY - ratio * chartHeight;
    const value = maxValue * ratio;
    return `<g>
      <line class="report-trend__grid-line" x1="${TREND_PAD.left}" x2="${TREND_WIDTH - TREND_PAD.right}" y1="${round(y)}" y2="${round(y)}"></line>
      <text class="report-trend__axis-label" x="${TREND_PAD.left - 12}" y="${round(y + 4)}">${esc(formatMetricValue(value, metric))}</text>
    </g>`;
  }).join("");

  const xTickIndexes = Array.from(new Set([
    0,
    Math.floor((points.length - 1) / 2),
    points.length - 1,
  ])).filter((index) => index >= 0 && index < svgPoints.length);
  const xTicks = xTickIndexes.map((index) => {
    const point = svgPoints[index];
    return `<text class="report-trend__axis-label report-trend__axis-label--x" x="${round(point.x)}" y="${TREND_HEIGHT - 10}">${esc(point.label)}</text>`;
  }).join("");

  const lineFor = (series: "total" | "input" | "output" | "cache", yKey: keyof Pick<SvgPoint, "totalY" | "inputY" | "outputY" | "cacheY">) =>
    `<path class="report-trend__line report-trend__line--${series}" d="${seriesPath(svgPoints.map((point) => ({ x: point.x, y: Number(point[yKey]) })))}"></path>`;
  const dotFor = (series: "total" | "input" | "output" | "cache", yKey: keyof Pick<SvgPoint, "totalY" | "inputY" | "outputY" | "cacheY">) =>
    svgPoints.map((point) =>
      `<circle class="report-trend__dot report-trend__dot--${series}" cx="${round(point.x)}" cy="${round(Number(point[yKey]))}" r="${series === "total" ? 3 : 2.4}"></circle>`,
    ).join("");

  const hitWidth = Math.max(18, Math.min(44, xStep || chartWidth));
  const hoverZones = svgPoints.map((point, index) => {
    const left = svgPoints.length === 1
      ? point.x - hitWidth / 2
      : index === 0
      ? TREND_PAD.left
      : index === svgPoints.length - 1
        ? point.x - hitWidth
        : point.x - hitWidth / 2;
    const boundedLeft = Math.max(TREND_PAD.left, Math.min(left, TREND_WIDTH - TREND_PAD.right - hitWidth));
    return `<g class="report-trend__interaction">
      <line class="report-trend__crosshair" x1="${round(point.x)}" x2="${round(point.x)}" y1="${TREND_PAD.top}" y2="${baselineY}"></line>
      <circle class="report-trend__active-point" cx="${round(point.x)}" cy="${round(point.totalY)}" r="5"></circle>
      <rect class="report-trend__hover-zone"
        x="${round(boundedLeft)}"
        y="${TREND_PAD.top}"
        width="${round(Math.min(hitWidth, TREND_WIDTH - TREND_PAD.right - boundedLeft))}"
        height="${chartHeight}"
        data-title="${esc(point.label)}"
        data-total="${point.total}"
        data-value="${esc(formatMetricValue(point.total, metric))}"
        data-input="${point.input}"
        data-output="${point.output}"
        data-cache="${point.cache}"
        data-requests="${point.requests}"></rect>
    </g>`;
  }).join("");

  const area = areaPath(svgPoints.map((point) => ({ x: point.x, y: point.totalY })), baselineY);
  const extraSeries = metric === "tokens"
    ? `${lineFor("cache", "cacheY")}
      ${lineFor("input", "inputY")}
      ${lineFor("output", "outputY")}
      ${dotFor("cache", "cacheY")}
      ${dotFor("input", "inputY")}
      ${dotFor("output", "outputY")}`
    : "";

  return `<div class="report-trend" data-report-trend data-metric="${esc(metric)}" data-metric-label="${esc(metricLabel(metric, copy))}" data-label-total="${esc(copy.total)}" data-label-input="${esc(copy.input)}" data-label-output="${esc(copy.output)}" data-label-cache="${esc(copy.cache)}" data-label-requests="${esc(copy.requests)}">
    <svg class="report-trend__svg" viewBox="0 0 ${TREND_WIDTH} ${TREND_HEIGHT}" role="img" aria-label="${esc(copy.dailyTrend)}">
      ${yTicks}
      <line class="report-trend__axis-line" x1="${TREND_PAD.left}" x2="${TREND_WIDTH - TREND_PAD.right}" y1="${baselineY}" y2="${baselineY}"></line>
      ${xTicks}
      <path class="report-trend__area report-trend__area--total" d="${area}"></path>
      ${extraSeries}
      ${lineFor("total", "totalY")}
      ${dotFor("total", "totalY")}
      ${hoverZones}
    </svg>
    <div class="report-trend__tooltip" role="tooltip" aria-hidden="true"></div>
  </div>`;
}

function localizedWorkHealthDetail(signal: WorkHealthSummary["signals"][number], copy: ReportCopy): string {
  const count = Number.parseInt(signal.value, 10);
  const countValue = Number.isFinite(count) ? count : 0;
  if (signal.kind === "attention") {
    return countValue > 0
      ? interpolate(copy.workHealthDetail.attention, { count: countValue })
      : copy.workHealthDetail.attentionZero;
  }
  if (signal.kind === "longest_wait") {
    return signal.value === "—"
      ? copy.workHealthDetail.longest_wait_zero
      : copy.workHealthDetail.longest_wait;
  }
  if (signal.kind === "unrecovered_failure") {
    return countValue > 0
      ? interpolate(copy.workHealthDetail.unrecovered_failure, { count: countValue })
      : copy.workHealthDetail.unrecovered_failure_zero;
  }
  if (signal.kind === "context_near_full") {
    const contextSessionCount = signal.sessionIds.length;
    return signal.disabledReason || signal.value === "—"
      ? copy.workHealthDetail.context_near_full_zero
      : interpolate(copy.workHealthDetail.context_near_full, { count: contextSessionCount });
  }
  if (signal.kind === "cost_anomaly") {
    return signal.value === "New" ? copy.workHealthDetail.cost_new : copy.workHealthDetail.cost_anomaly;
  }
  return signal.detail;
}

function renderWorkHealth(workHealth: HtmlReportInput["workHealth"], copy: ReportCopy): string {
  const signals = workHealth?.signals ?? [];
  if (signals.length === 0) return "";

  const cards = signals.map((signal) => `<article class="report-health__signal report-health__signal--${esc(signal.tone)}">
    <div class="report-health__label">${esc(copy.workHealthSignal[signal.kind] ?? signal.label)}</div>
    <div class="report-health__value">${esc(signal.value)}</div>
    <div class="report-health__detail">${esc(localizedWorkHealthDetail(signal, copy))}</div>
  </article>`).join("");

  return `<h2>${esc(copy.workHealth)}</h2>
  <div class="report-health">${cards}</div>`;
}

function renderTrendLegend(metric: AnalyticsMetric = "tokens", copy: ReportCopy = REPORT_COPY.en): string {
  if (metric !== "tokens") {
    return `<div class="chart-legend">
      <span class="legend-item"><span class="legend-dot legend-dot--total"></span>${esc(metricLabel(metric, copy))}</span>
    </div>`;
  }
  return `<div class="chart-legend">
    <span class="legend-item"><span class="legend-dot legend-dot--total"></span>${esc(copy.total)}</span>
    <span class="legend-item"><span class="legend-dot legend-dot--input"></span>${esc(copy.input)}</span>
    <span class="legend-item"><span class="legend-dot legend-dot--output"></span>${esc(copy.output)}</span>
    <span class="legend-item"><span class="legend-dot legend-dot--cache"></span>${esc(copy.cache)}</span>
  </div>`;
}

function reportTrendScript(): string {
  return `<script>
(() => {
  window.CodePalReportTrend = true;
  const formatNumber = (value) => {
    const number = Number(value || 0);
    if (number >= 1000000) return (number / 1000000).toFixed(1) + "M";
    if (number >= 1000) return (number / 1000).toFixed(1) + "K";
    return String(Math.round(number));
  };
  for (const chart of document.querySelectorAll("[data-report-trend]")) {
    const tooltip = chart.querySelector(".report-trend__tooltip");
    if (!tooltip) continue;
    const metric = chart.dataset.metric || "tokens";
    const metricLabel = chart.dataset.metricLabel || "Total";
    const labelTotal = chart.dataset.labelTotal || "Total";
    const labelInput = chart.dataset.labelInput || "Input";
    const labelOutput = chart.dataset.labelOutput || "Output";
    const labelCache = chart.dataset.labelCache || "Cache";
    const labelRequests = chart.dataset.labelRequests || "Requests";
    for (const zone of chart.querySelectorAll(".report-trend__hover-zone")) {
      zone.addEventListener("mouseenter", () => {
        let rows = '<div class="report-trend__tooltip-row"><span>' + metricLabel + '</span><strong>' + (zone.dataset.value || formatNumber(zone.dataset.total)) + '</strong></div>';
        if (metric === "tokens") {
          rows = '<div class="report-trend__tooltip-row"><span>' + labelTotal + '</span><strong>' + formatNumber(zone.dataset.total) + '</strong></div>' +
            '<div class="report-trend__tooltip-row"><span>' + labelInput + '</span><strong>' + formatNumber(zone.dataset.input) + '</strong></div>' +
            '<div class="report-trend__tooltip-row"><span>' + labelOutput + '</span><strong>' + formatNumber(zone.dataset.output) + '</strong></div>' +
            '<div class="report-trend__tooltip-row"><span>' + labelCache + '</span><strong>' + formatNumber(zone.dataset.cache) + '</strong></div>';
        }
        rows += '<div class="report-trend__tooltip-row"><span>' + labelRequests + '</span><strong>' + formatNumber(zone.dataset.requests) + '</strong></div>';
        tooltip.innerHTML = '<div class="report-trend__tooltip-title">' + zone.dataset.title + '</div>' + rows;
        tooltip.setAttribute("aria-hidden", "false");
        tooltip.classList.add("report-trend__tooltip--visible");
      });
      zone.addEventListener("mousemove", (event) => {
        const bounds = chart.getBoundingClientRect();
        const tooltipWidth = tooltip.offsetWidth || 190;
        const left = Math.min(bounds.width - tooltipWidth - 12, Math.max(12, event.clientX - bounds.left + 14));
        const top = Math.max(12, event.clientY - bounds.top - 110);
        tooltip.style.left = left + "px";
        tooltip.style.top = top + "px";
      });
      zone.addEventListener("mouseleave", () => {
        tooltip.classList.remove("report-trend__tooltip--visible");
        tooltip.setAttribute("aria-hidden", "true");
      });
    }
  }
})();
</script>`;
}

export function generateHtmlReport(input: HtmlReportInput): string {
  const locale = input.locale ?? input.redaction?.locale ?? "en";
  const copy = REPORT_COPY[locale] ?? REPORT_COPY.en;

  const totalInput = input.daily.reduce((s, d) => s + d.inputTokens, 0);
  const totalOutput = input.daily.reduce((s, d) => s + d.outputTokens, 0);
  const totalCacheRead = input.daily.reduce((s, d) => s + d.cacheReadTokens, 0);
  const totalCacheCreation = input.daily.reduce((s, d) => s + d.cacheCreationTokens, 0);
  const totalTokens = totalInput + totalOutput + totalCacheRead + totalCacheCreation;
  const totalRequests = input.daily.reduce((s, d) => s + d.requestCount, 0);
  const cacheHitRate = totalCacheRead + totalInput > 0
    ? totalCacheRead / (totalCacheRead + totalInput + totalCacheCreation) : 0;
  const projectCost = (input.byProject ?? []).reduce((sum, project) => sum + (project.estimatedCost ?? 0), 0);
  const totalCost = projectCost > 0
    ? projectCost
    : input.byModel.reduce((s, m) => s + estimateCost(m, input.pricing, m.model), 0);
  const topAgent = input.byAgent?.[0];
  const topModel = input.byModel[0];

  // Session stats
  const byAgent = new Map<string, Array<{ status: string; count: number }>>();
  for (const s of input.sessionStats) {
    const arr = byAgent.get(s.agent) ?? [];
    arr.push({ status: s.status, count: s.count });
    byAgent.set(s.agent, arr);
  }
  let sessionRows = "";
  for (const [agent, statuses] of byAgent) {
    const total = statuses.reduce((s, x) => s + x.count, 0);
    const label = AGENT_LABELS[agent] ?? agent;
    const parts = statuses.map((s) => `${s.count} ${statusLabel(s.status, copy)}`).join(", ");
    sessionRows += `<tr><td>${esc(label)}</td><td class="num">${total}</td><td>${esc(parts)}</td></tr>\n`;
  }

  const trendPoints = buildReportTrendPoints(input);
  const trendChart = renderTrendChart(trendPoints, input.metric ?? "tokens", copy);
  const workHealth = renderWorkHealth(input.workHealth, copy);

  // Model table
  let modelRows = "";
  for (const m of input.byModel) {
    const cost = estimateCost(m, input.pricing, m.model);
    const modelTotal = m.inputTokens + m.cacheReadTokens + m.cacheCreationTokens;
    const modelCacheRate = modelTotal > 0 ? m.cacheReadTokens / modelTotal : 0;
    const modelDisplayName = input.redaction?.redactModelNames ? copy.redactedModel : m.model;
    modelRows += `<tr>
      <td><span class="agent-tag">${esc(m.agent)}</span>${esc(modelDisplayName)}</td>
      <td class="num">${m.requestCount}</td>
      <td class="num">${fmtTokens(m.inputTokens)}</td>
      <td class="num">${fmtTokens(m.outputTokens)}</td>
      <td class="num">${modelCacheRate > 0 ? Math.round(modelCacheRate * 100) + "%" : "&mdash;"}</td>
      <td class="num">${fmtTokens(m.cacheReadTokens)}</td>
      <td class="num">${fmtCost(cost, locale)}</td>
    </tr>\n`;
  }

  let projectRows = "";
  for (const project of sortProjectRows(input.byProject ?? [])) {
    const inputLikeTotal = project.inputTokens + project.cacheReadTokens + project.cacheCreationTokens;
    const cacheRate = inputLikeTotal > 0 ? project.cacheReadTokens / inputLikeTotal : 0;
    const projectName = project.projectPath === UNKNOWN_PROJECT_PATH || isUnknownProjectPath(project.projectPath)
      ? copy.unknownProject
      : project.projectName;
    projectRows += `<tr>
      <td title="${isUnknownProjectPath(project.projectPath) ? "" : esc(project.projectPath)}">${esc(projectName)}</td>
      <td class="num">${project.requestCount}</td>
      <td class="num">${fmtTokens(project.totalTokens)}</td>
      <td class="num">${fmtTokens(project.inputTokens)}</td>
      <td class="num">${fmtTokens(project.outputTokens)}</td>
      <td class="num">${cacheRate > 0 ? Math.round(cacheRate * 100) + "%" : "&mdash;"}</td>
      <td class="num">${fmtCost(project.estimatedCost ?? 0, locale)}</td>
    </tr>\n`;
  }

  let agentRows = "";
  for (const agent of input.byAgent ?? []) {
    const totalInputLike = agent.inputTokens + agent.cacheReadTokens + agent.cacheCreationTokens;
    const cacheRate = totalInputLike > 0 ? agent.cacheReadTokens / totalInputLike : 0;
    agentRows += `<tr>
      <td>${esc(AGENT_LABELS[agent.agent] ?? agent.agent)}</td>
      <td class="num">${agent.requestCount}</td>
      <td class="num">${fmtTokens(agent.totalTokens)}</td>
      <td class="num">${fmtTokens(agent.inputTokens)}</td>
      <td class="num">${fmtTokens(agent.outputTokens)}</td>
      <td class="num">${cacheRate > 0 ? Math.round(cacheRate * 100) + "%" : "&mdash;"}</td>
    </tr>\n`;
  }

  let topSessionRows = "";
  let sessionCounter = 0;
  for (const session of input.topSessions ?? []) {
    sessionCounter++;
    const redactTitles = input.redaction?.redactSessionTitles;
    const redactModels = input.redaction?.redactModelNames;
    const sessionTitle = redactTitles
      ? `${copy.redactedSessionPrefix} ${sessionCounter}`
      : (session.title?.trim() || shortSessionId(session.sessionId));
    const secondaryId = redactTitles ? "" : (session.title?.trim() ? shortSessionId(session.sessionId) : "");
    const modelLabel = redactModels ? copy.redactedModel : session.model;
    const context = input.sessionContexts?.[session.sessionId];
    const percent = contextPercent(context);
    const contextText =
      percent === null
        ? "&mdash;"
        : `<span class="report-context report-context--${contextTone(percent)}" ${
            contextDetail(context) ? `title="${esc(contextDetail(context))}"` : ""
          }>${percent}%</span>`;
    topSessionRows += `<tr>
      <td>
        <div class="session-title">${esc(sessionTitle)}</div>
        ${secondaryId ? `<div class="session-id">${esc(secondaryId)}</div>` : ""}
      </td>
      <td>${esc(AGENT_LABELS[session.agent] ?? session.agent)}</td>
      <td>${esc(modelLabel)}</td>
      <td class="num">${session.requestCount}</td>
      <td class="num">${fmtTokens(session.totalTokens)}</td>
      <td class="num">${contextText}</td>
      <td class="num">${fmtDateTime(session.lastSeenAt, locale)}</td>
    </tr>\n`;
  }

  const importStatus = input.importStatus;
  const importSummary = importStatus
    ? `${copy.backfill}: ${
        importStatus.completedAt ? fmtDateTime(importStatus.completedAt, locale) : copy.notCompleted
      } · ${copy.claudeRows}: ${importStatus.claudeRowsImported} · ${copy.codexRows}: ${importStatus.codexRowsImported}${
        importStatus.lastError ? ` · ${copy.error}: ${esc(importStatus.lastError)}` : ""
      }`
    : "";

  return `<!DOCTYPE html>
<html lang="${copy.htmlLang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(copy.title)} — ${esc(input.startDate)} ~ ${esc(input.endDate)}</title>
<style>
  :root {
    --bg: #0a0f15; --bg2: #121925; --bg3: #182130;
    --border: #283243; --text: #edf4ff; --muted: #8b98ad;
    --accent: #79a8ff; --green: #3fe0c2; --radius: 10px;
  }
  *, *::before, *::after { box-sizing: border-box; }
  body {
    margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
    font-size: 14px; line-height: 1.5; color: var(--text);
    background: linear-gradient(180deg, #091018, #0d141c 40%, #101823);
    min-height: 100vh; padding: clamp(22px, 3vw, 42px) clamp(12px, 2.5vw, 36px);
  }
  .container { width: 100%; max-width: 1680px; margin: 0 auto; }
  h1 { font-size: 24px; font-weight: 700; margin: 0 0 4px; }
  .subtitle { color: var(--muted); font-size: 14px; margin: 0 0 32px; }
  h2 {
    font-size: 13px; font-weight: 700; letter-spacing: 0.06em;
    text-transform: uppercase; color: var(--muted); margin: 32px 0 12px;
  }

  /* Hero grid */
  .hero-grid {
    display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
    gap: 12px; margin-bottom: 32px;
  }
  .hero-card {
    padding: 16px 18px; border-radius: var(--radius);
    border: 1px solid var(--border); background: var(--bg2);
  }
  .hero-card .label { font-size: 11px; font-weight: 500; color: var(--muted); margin-bottom: 6px; }
  .hero-card .value { font-size: 22px; font-weight: 700; }
  .hero-card .detail { margin-top: 3px; color: var(--muted); font-size: 12px; }

  /* Trend chart */
  .report-trend {
    position: relative; padding: 16px 18px 12px; border-radius: var(--radius);
    border: 1px solid var(--border); background: #0d141c; margin-bottom: 10px;
  }
  .report-trend__svg { width: 100%; min-height: 260px; display: block; overflow: visible; }
  .report-trend__grid-line { stroke: rgba(237,244,255,0.08); stroke-width: 1; }
  .report-trend__axis-line { stroke: rgba(237,244,255,0.14); stroke-width: 1; }
  .report-trend__axis-label {
    fill: var(--muted); font-size: 11px; font-weight: 600;
    font-variant-numeric: tabular-nums; text-anchor: end;
  }
  .report-trend__axis-label--x { text-anchor: middle; }
  .report-trend__area--total { fill: rgba(121,168,255,0.12); }
  .report-trend__line {
    fill: none; stroke-linecap: round; stroke-linejoin: round;
    stroke-width: 2.4; vector-effect: non-scaling-stroke;
  }
  .report-trend__line--total { stroke: #6f9bff; stroke-width: 2.8; }
  .report-trend__line--input { stroke: #54d6c0; }
  .report-trend__line--output { stroke: #9b78ff; }
  .report-trend__line--cache { stroke: #e2ad55; }
  .report-trend__dot { vector-effect: non-scaling-stroke; stroke: #0d141c; stroke-width: 1.2; }
  .report-trend__dot--total { fill: #6f9bff; }
  .report-trend__dot--input { fill: #54d6c0; }
  .report-trend__dot--output { fill: #9b78ff; }
  .report-trend__dot--cache { fill: #e2ad55; }
  .report-trend__crosshair {
    opacity: 0; stroke: rgba(237,244,255,0.28); stroke-dasharray: 4 4; stroke-width: 1;
    vector-effect: non-scaling-stroke;
  }
  .report-trend__active-point {
    opacity: 0; fill: #6f9bff; stroke: #edf4ff; stroke-width: 1.5;
    vector-effect: non-scaling-stroke;
  }
  .report-trend__hover-zone { fill: transparent; pointer-events: all; cursor: crosshair; }
  .report-trend__interaction:hover .report-trend__crosshair,
  .report-trend__interaction:hover .report-trend__active-point { opacity: 1; }
  .report-trend__tooltip {
    position: absolute; z-index: 5; min-width: 186px; padding: 11px 12px;
    border-radius: 9px; border: 1px solid #33443c; background: #070908;
    color: #f4f1e8; box-shadow: 0 18px 48px rgba(0,0,0,0.38);
    pointer-events: none; opacity: 0; transform: translateY(4px);
    transition: opacity 0.12s ease, transform 0.12s ease;
  }
  .report-trend__tooltip--visible { opacity: 1; transform: translateY(0); }
  .report-trend__tooltip-title {
    margin-bottom: 8px; font-size: 12px; font-weight: 700;
    letter-spacing: 0.04em; font-variant-numeric: tabular-nums;
  }
  .report-trend__tooltip-row {
    display: flex; align-items: center; justify-content: space-between; gap: 18px;
    font-size: 12px; color: rgba(244,241,232,0.74);
  }
  .report-trend__tooltip-row strong {
    color: #f4f1e8; font-variant-numeric: tabular-nums; font-size: 12px;
  }
  .chart-legend {
    display: flex; gap: 16px; justify-content: center; font-size: 11px; color: var(--muted);
    margin-bottom: 32px;
  }
  .legend-item { display: flex; align-items: center; gap: 5px; }
  .legend-dot {
    width: 8px; height: 8px; border-radius: 2px; display: inline-block;
  }
  .legend-dot--total { background: #6f9bff; }
  .legend-dot--input { background: #54d6c0; }
  .legend-dot--output { background: #9b78ff; }
  .legend-dot--cache { background: #e2ad55; }

  /* Work Health */
  .report-health {
    display: grid; grid-template-columns: repeat(auto-fit, minmax(155px, 1fr));
    gap: 10px; margin-bottom: 28px;
  }
  .report-health__signal {
    padding: 13px 14px; border-radius: var(--radius);
    border: 1px solid var(--border); background: var(--bg2);
  }
  .report-health__signal--warning { border-color: rgba(226,173,85,0.45); }
  .report-health__signal--danger { border-color: rgba(255,91,86,0.45); }
  .report-health__signal--info { border-color: rgba(111,155,255,0.4); }
  .report-health__label { color: var(--muted); font-size: 11px; margin-bottom: 5px; }
  .report-health__value { font-size: 19px; font-weight: 800; margin-bottom: 3px; }
  .report-health__detail { color: var(--muted); font-size: 11px; line-height: 1.35; }

  /* Tables */
  .table-wrap {
    width: 100%; overflow-x: auto; border-radius: var(--radius);
    border: 1px solid var(--border); background: var(--bg2);
  }
  table {
    width: 100%; border-collapse: collapse; font-size: 13px;
    border-radius: var(--radius); overflow: hidden;
    background: var(--bg2); table-layout: auto; min-width: 760px;
  }
  .table--wide { min-width: 1040px; }
  .table--sessions { min-width: 560px; }
  thead { background: rgba(255,255,255,0.03); }
  th {
    text-align: left; padding: 10px 14px; font-weight: 600; font-size: 11px;
    color: var(--muted); letter-spacing: 0.03em; border-bottom: 1px solid var(--border);
  }
  td { padding: 10px 14px; border-bottom: 1px solid rgba(40,50,67,0.5); white-space: nowrap; }
  tbody tr:last-child td { border-bottom: none; }
  tbody tr:hover { background: rgba(255,255,255,0.02); }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  th.num { text-align: right; }
  .agent-tag { opacity: 0.5; margin-right: 6px; font-size: 11px; }
  .session-title { font-weight: 600; overflow-wrap: anywhere; white-space: normal; min-width: 240px; }
  .session-id { margin-top: 3px; color: var(--muted); font-size: 11px; font-variant-numeric: tabular-nums; }
  .report-context {
    display: inline-flex; align-items: center; justify-content: flex-end;
    min-width: 48px; padding: 2px 7px; border-radius: 999px;
    border: 1px solid rgba(139,152,173,0.26); background: rgba(139,152,173,0.08);
    color: var(--text); font-weight: 700;
  }
  .report-context--notice { border-color: rgba(121,168,255,0.42); background: rgba(121,168,255,0.12); color: #bcd0ff; }
  .report-context--warning { border-color: rgba(226,173,85,0.52); background: rgba(226,173,85,0.13); color: #ffd392; }
  .report-context--danger { border-color: rgba(255,91,86,0.55); background: rgba(255,91,86,0.14); color: #ffaaa7; }

  .footer { margin-top: 48px; color: var(--muted); font-size: 11px; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <h1>${esc(copy.title)}</h1>
  <p class="subtitle">${esc(input.startDate)} ~ ${esc(input.endDate)}</p>

  ${sessionRows ? `<h2>${esc(copy.sessions)}</h2>
  <div class="table-wrap"><table class="table--sessions"><thead><tr><th>${esc(copy.agent)}</th><th class="num">${esc(copy.total)}</th><th>${esc(copy.breakdown)}</th></tr></thead>
  <tbody>${sessionRows}</tbody></table></div>` : ""}

  <h2>${esc(copy.tokenUsage)}</h2>
  <div class="hero-grid">
    <div class="hero-card"><div class="label">${esc(copy.totalTokens)}</div><div class="value">${fmtHeroTokens(totalTokens)}</div></div>
    <div class="hero-card"><div class="label">${esc(copy.requests)}</div><div class="value">${totalRequests}</div></div>
    <div class="hero-card"><div class="label">${esc(copy.input)}</div><div class="value">${fmtHeroTokens(totalInput)}</div></div>
    <div class="hero-card"><div class="label">${esc(copy.output)}</div><div class="value">${fmtHeroTokens(totalOutput)}</div></div>
    <div class="hero-card"><div class="label">${esc(copy.topAgent)}</div><div class="value">${topAgent ? esc(AGENT_LABELS[topAgent.agent] ?? topAgent.agent) : "&mdash;"}</div>${topAgent ? `<div class="detail">${fmtHeroTokens(topAgent.totalTokens)} tokens</div>` : ""}</div>
    <div class="hero-card"><div class="label">${esc(copy.topModel)}</div><div class="value">${topModel ? esc(input.redaction?.redactModelNames ? copy.redactedModel : topModel.model) : "&mdash;"}</div>${topModel ? `<div class="detail">${esc(AGENT_LABELS[topModel.agent] ?? topModel.agent)}</div>` : ""}</div>
    <div class="hero-card"><div class="label">${esc(copy.cacheHit)}</div><div class="value">${Math.round(cacheHitRate * 100)}%</div></div>
    <div class="hero-card"><div class="label">${esc(copy.estimatedCost)}</div><div class="value">${fmtHeroCost(totalCost, locale)}</div></div>
  </div>

  ${workHealth}

  ${trendChart ? `<h2>${esc(copy.dailyTrend)}</h2>
  ${trendChart}
  ${renderTrendLegend(input.metric ?? "tokens", copy)}` : ""}

  ${projectRows ? `<h2>${esc(copy.compactBreakdown)}</h2>
  <div class="table-wrap"><table class="table--wide"><thead><tr>
    <th>${esc(copy.project)}</th><th class="num">${esc(copy.requests)}</th><th class="num">${esc(copy.totalTokens)}</th>
    <th class="num">${esc(copy.input)}</th><th class="num">${esc(copy.output)}</th><th class="num">${esc(copy.cacheHit)}</th><th class="num">${esc(copy.estimatedCost)}</th>
  </tr></thead><tbody>${projectRows}</tbody></table></div>` : ""}

  ${input.byModel.length > 0 ? `<h2>${esc(copy.byModel)}</h2>
  <div class="table-wrap"><table class="table--wide"><thead><tr>
    <th>${esc(copy.model)}</th><th class="num">${esc(copy.requests)}</th><th class="num">${esc(copy.input)}</th>
    <th class="num">${esc(copy.output)}</th><th class="num">${esc(copy.cacheHit)}</th><th class="num">${esc(copy.cacheRead)}</th><th class="num">${esc(copy.cost)}</th>
  </tr></thead><tbody>${modelRows}</tbody></table></div>` : ""}

  ${agentRows ? `<h2>${esc(copy.byAgent)}</h2>
  <div class="table-wrap"><table><thead><tr>
    <th>${esc(copy.agent)}</th><th class="num">${esc(copy.requests)}</th><th class="num">${esc(copy.total)}</th>
    <th class="num">${esc(copy.input)}</th><th class="num">${esc(copy.output)}</th><th class="num">${esc(copy.cacheHit)}</th>
  </tr></thead><tbody>${agentRows}</tbody></table></div>` : ""}

  ${topSessionRows ? `<h2>${esc(copy.topSessions)}</h2>
  <div class="table-wrap"><table class="table--wide"><thead><tr>
    <th>${esc(copy.session)}</th><th>${esc(copy.agent)}</th><th>${esc(copy.model)}</th><th class="num">${esc(copy.requests)}</th>
    <th class="num">${esc(copy.tokens)}</th><th class="num">${esc(copy.context)}</th><th class="num">${esc(copy.lastSeen)}</th>
  </tr></thead><tbody>${topSessionRows}</tbody></table></div>` : ""}

  ${importSummary ? `<p class="footer">${importSummary}</p>` : ""}

  ${input.redaction?.redactSessionTitles || input.redaction?.redactModelNames
    ? `<p class="footer" style="color:#e2a03f">${esc(copy.redacted)}: ${[
        input.redaction?.redactSessionTitles ? copy.redactedSessionTitles : "",
        input.redaction?.redactModelNames ? copy.redactedModelNames : "",
      ].filter(Boolean).join(", ")}</p>`
    : ""}
  <div class="footer">${esc(copy.generatedBy)} · ${fmtDateTime(Date.now(), locale)}</div>
</div>
${reportTrendScript()}
</body>
</html>`;
}
