import type { ResolvedLocale } from "../shared/i18nTypes";
import { isSessionStatus, type ActivityItem, type SessionStatus } from "../shared/sessionTypes";
import type { MonitorSessionRow } from "./monitorSession";

export type DailyWorkReviewSource = {
  id: string;
  tool: string;
  status: SessionStatus | string;
  title?: string | null;
  task?: string | null;
  updatedAt: number;
  lastUserMessageAt?: number | null;
  activityItems?: ActivityItem[];
  collapsedSummary?: string;
  titleLabel?: string;
  isManaged?: boolean;
  managedTaskTitle?: string;
};

export type DailyWorkReviewEntry = {
  id: string;
  title: string;
  detail: string;
  agent: string;
  status: SessionStatus;
  source: "managed" | "observed";
  timestamp: number;
};

export type DailyWorkReviewDay = {
  key: string;
  isToday: boolean;
  dateLabel: string;
  weekdayLabel: string;
  relativeLabel: string;
  summaryText: string;
  sessionCount: number;
  completedCount: number;
  ongoingCount: number;
  managedCount: number;
  observedCount: number;
  agents: string[];
  completed: DailyWorkReviewEntry[];
  ongoing: DailyWorkReviewEntry[];
  entries: DailyWorkReviewEntry[];
};

type BuildDailyWorkReviewOptions = {
  locale?: ResolvedLocale;
  now?: number;
  maxDays?: number;
};

const MS_PER_DAY = 24 * 60 * 60 * 1000;

function dateKey(timestamp: number): string {
  const date = new Date(timestamp);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function startOfDay(timestamp: number): number {
  const date = new Date(timestamp);
  date.setHours(0, 0, 0, 0);
  return date.getTime();
}

function startOfWeek(timestamp: number): number {
  const date = new Date(startOfDay(timestamp));
  const daysSinceMonday = (date.getDay() + 6) % 7;
  date.setDate(date.getDate() - daysSinceMonday);
  return date.getTime();
}

function relativeLabel(timestamp: number, now: number, locale: ResolvedLocale): string {
  const diffDays = Math.round((startOfDay(now) - startOfDay(timestamp)) / MS_PER_DAY);
  const nowWeekStart = startOfWeek(now);
  const timestampWeekStart = startOfWeek(timestamp);
  const isThisWeek = timestampWeekStart === nowWeekStart;
  const isLastWeek = timestampWeekStart === nowWeekStart - 7 * MS_PER_DAY;
  if (locale === "zh-CN") {
    if (diffDays === 0) return "今天";
    if (diffDays === 1) return "昨天";
    if (isThisWeek) return "本周";
    if (isLastWeek) return "上周";
    return "更早";
  }
  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Yesterday";
  if (isThisWeek) return "This week";
  if (isLastWeek) return "Last week";
  return "Earlier";
}

function formatDate(timestamp: number, locale: ResolvedLocale): string {
  return new Date(timestamp).toLocaleDateString(locale, {
    year: "numeric",
    month: "numeric",
    day: "numeric",
  });
}

function formatWeekday(timestamp: number, locale: ResolvedLocale): string {
  return new Date(timestamp).toLocaleDateString(locale, {
    weekday: "short",
  });
}

function cleanText(value: string | undefined): string {
  return (value ?? "").replace(/\s+/g, " ").trim();
}

function isJsonOnlyText(value: string): boolean {
  const trimmed = value.trim();
  if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) {
    return false;
  }
  try {
    JSON.parse(trimmed);
    return true;
  } catch {
    return false;
  }
}

function isLowValueReviewText(value: string | undefined): boolean {
  const text = cleanText(value);
  if (!text) return true;
  const lower = text.toLowerCase();
  return (
    lower.startsWith("the following is the codex agent history whose request action you are assessing") ||
    lower.startsWith("the following is the codex agent history added since your last approval assessment") ||
    lower.startsWith("<local-command-caveat>") ||
    lower.startsWith("caveat: the messages below were generated by the user") ||
    lower.startsWith("# files mentioned by the user") ||
    lower.startsWith("files mentioned by the user") ||
    lower.startsWith("wall time:") ||
    lower.startsWith("process exited with code") ||
    lower.startsWith("chunk id:") ||
    lower.startsWith("auto-inferred:") ||
    lower.includes("/users/") ||
    lower === "exec_command completed" ||
    lower === "write_stdin completed" ||
    lower === "working" ||
    isJsonOnlyText(text)
  );
}

function truncate(value: string, maxLength: number): string {
  if (value.length <= maxLength) return value;
  return `${value.slice(0, maxLength - 1)}…`;
}

function normalizeStatus(status: string): SessionStatus {
  return isSessionStatus(status) ? status : "completed";
}

function fallbackTitle(row: DailyWorkReviewSource): string {
  return cleanText(
    row.managedTaskTitle ||
      row.titleLabel ||
      row.title ||
      row.task ||
      row.collapsedSummary ||
      `${row.tool} session`,
  );
}

function fallbackDetail(row: DailyWorkReviewSource, title: string): string {
  const summary = cleanText(row.collapsedSummary);
  if (summary && summary !== title && !isLowValueReviewText(summary)) {
    return truncate(summary, 128);
  }
  const item = row.activityItems?.find((activity) => !isLowValueReviewText(activity.body));
  const body = cleanText(item?.body);
  return body && body !== title ? truncate(body, 128) : "";
}

function buildEntry(row: DailyWorkReviewSource): DailyWorkReviewEntry {
  const title = truncate(fallbackTitle(row), 80);
  return {
    id: row.id,
    title,
    detail: fallbackDetail(row, title),
    agent: row.tool,
    status: normalizeStatus(row.status),
    source: row.isManaged ? "managed" : "observed",
    timestamp: row.lastUserMessageAt ?? row.updatedAt,
  };
}

function isCompleted(status: SessionStatus): boolean {
  return status === "completed" || status === "idle";
}

function isOngoing(status: SessionStatus): boolean {
  return status === "running" || status === "waiting" || status === "offline";
}

function sortEntries(entries: DailyWorkReviewEntry[]): DailyWorkReviewEntry[] {
  return [...entries].sort((a, b) => b.timestamp - a.timestamp);
}

function titleList(entries: DailyWorkReviewEntry[], locale: ResolvedLocale): string {
  const maxSummaryTitleLength = locale === "zh-CN" ? 36 : 52;
  const titles = entries
    .slice(0, 2)
    .map((entry) => truncate(entry.title, maxSummaryTitleLength));
  if (entries.length <= 2) {
    return locale === "zh-CN" ? titles.join("、") : titles.join(", ");
  }
  if (locale === "zh-CN") {
    return `${titles.join("、")} 等 ${entries.length} 项`;
  }
  return `${titles.join(", ")}, and ${entries.length - 2} more`;
}

function buildSummaryText(
  completed: DailyWorkReviewEntry[],
  ongoing: DailyWorkReviewEntry[],
  locale: ResolvedLocale,
): string {
  const focus = titleList([...completed, ...ongoing], locale);
  if (locale === "zh-CN") {
    if (completed.length > 0 && ongoing.length > 0) {
      return `完成 ${completed.length} 项，跟进 ${ongoing.length} 项。重点：${focus}。`;
    }
    if (completed.length > 0) {
      return `完成 ${completed.length} 项。重点：${focus}。`;
    }
    if (ongoing.length > 0) {
      return `跟进 ${ongoing.length} 项。重点：${focus}。`;
    }
    return "这一天没有可回顾的已完成或跟进中会话。";
  }

  if (completed.length > 0 && ongoing.length > 0) {
    return `${completed.length} completed, ${ongoing.length} in progress. Focus: ${focus}.`;
  }
  if (completed.length > 0) {
    return `${completed.length} completed. Focus: ${focus}.`;
  }
  if (ongoing.length > 0) {
    return `${ongoing.length} in progress. Focus: ${focus}.`;
  }
  return "No completed or in-progress sessions to review for this day.";
}

export function buildDailyWorkReview(
  rows: Array<DailyWorkReviewSource | MonitorSessionRow>,
  options: BuildDailyWorkReviewOptions = {},
): DailyWorkReviewDay[] {
  const locale = options.locale ?? "en";
  const now = options.now ?? Date.now();
  const maxDays = options.maxDays ?? 14;
  const grouped = new Map<string, DailyWorkReviewEntry[]>();
  const dedupedRows = new Map<string, DailyWorkReviewSource | MonitorSessionRow>();

  for (const row of rows) {
    dedupedRows.set(row.id, row);
  }

  for (const row of dedupedRows.values()) {
    const timestamp = row.lastUserMessageAt ?? row.updatedAt;
    if (!Number.isFinite(timestamp)) {
      continue;
    }
    const status = normalizeStatus(row.status);
    const isToday = startOfDay(timestamp) === startOfDay(now);
    if (status === "error") {
      continue;
    }
    if (!isToday && !isCompleted(status)) {
      continue;
    }
    if (isLowValueReviewText(row.managedTaskTitle || row.titleLabel || row.title || row.task)) {
      continue;
    }
    const key = dateKey(timestamp);
    grouped.set(key, [...(grouped.get(key) ?? []), buildEntry(row)]);
  }

  return Array.from(grouped.entries())
    .map(([key, entries]) => {
      const sortedEntries = sortEntries(entries);
      const timestamp = sortedEntries[0]?.timestamp ?? now;
      const completed = sortedEntries.filter((entry) => isCompleted(entry.status));
      const ongoing = sortedEntries.filter((entry) => isOngoing(entry.status));
      const agents = Array.from(new Set(sortedEntries.map((entry) => entry.agent))).sort();
      const managedCount = sortedEntries.filter((entry) => entry.source === "managed").length;

      return {
        key,
        isToday: startOfDay(timestamp) === startOfDay(now),
        dateLabel: formatDate(timestamp, locale),
        weekdayLabel: formatWeekday(timestamp, locale),
        relativeLabel: relativeLabel(timestamp, now, locale),
        summaryText: buildSummaryText(completed, ongoing, locale),
        sessionCount: sortedEntries.length,
        completedCount: completed.length,
        ongoingCount: ongoing.length,
        managedCount,
        observedCount: sortedEntries.length - managedCount,
        agents,
        completed,
        ongoing,
        entries: sortedEntries,
      };
    })
    .sort((a, b) => b.key.localeCompare(a.key))
    .slice(0, maxDays);
}
